# Generated by Django 3.0.5 on 2020-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('beres', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['beres', 'tanggal'],
            },
        ),
    ]
